In [1]:
import time
import numpy as np

n=int(input("Enter the matrix size: "))
arr1 = np.random.randint(1,10,size=(n,n))
print(arr1)
arr2 = np.random.randint(1,10,size=(n,n))
print(arr2)
result =np.zeros([n, n], dtype = int)
# iterating by row of array1
start = time.time( )
for i in range(len(arr1)):
    # iterating by column by array2
    for j in range(len(arr2[0])):
        # iterating by rows of array2
        for k in range(len(arr2)):
            result[i][j] += arr1[i][k] * arr2[k][j]
end = time.time( )
print("The complete time taken for execution of above program is :", end-start)
for r in result:
    print(r)


Enter the matrix size:  32


[[6 9 9 ... 5 6 6]
 [9 1 1 ... 1 3 4]
 [8 3 5 ... 6 9 9]
 ...
 [7 6 6 ... 1 1 9]
 [6 3 8 ... 9 2 1]
 [7 8 5 ... 7 4 9]]
[[9 3 1 ... 6 8 3]
 [3 4 4 ... 2 6 8]
 [8 7 4 ... 4 1 9]
 ...
 [4 4 8 ... 3 6 5]
 [5 2 1 ... 5 2 5]
 [7 1 4 ... 5 4 1]]
The complete time taken for execution of above program is : 0.08521556854248047
[ 982  859  712  796  770  645  895  928  841  834  855  782  766 1008
  825  870  895  794  868  901  792  904  882  933  862  954  965  941
  720  844  823  834]
[959 942 830 834 658 643 865 858 907 848 771 824 815 948 870 883 895 776
 989 864 777 923 839 854 780 892 953 881 777 884 845 797]
[750 742 697 707 568 602 725 844 755 812 756 711 675 942 739 745 745 799
 801 755 648 800 734 739 684 836 849 788 562 752 720 663]
[858 821 770 794 665 651 927 961 810 804 816 809 786 976 811 855 871 807
 836 901 694 832 796 869 774 892 894 814 775 924 780 779]
[979 847 722 828 731 690 896 872 872 856 807 774 807 974 757 899 832 732
 909 851 753 878 806 862 829 973 978 871 722 784 7