In [11]:
import time
import numpy as np

n=int(input("Enter the matrix size: "))
arr1 = np.random.uniform(1,10,size=(n,n))
print(arr1)
arr2 = np.random.uniform(1,10,size=(n,n))
print(arr2)
result =np.zeros([n, n], dtype = float)
# iterating by row of array1
start = time.time( )
for i in range(len(arr1)):
    # iterating by column by array2
    for j in range(len(arr2[0])):
        # iterating by rows of array2
        for k in range(len(arr2)):
            result[i][j] += arr1[i][k] * arr2[k][j]
end = time.time( )
print("The complete time taken for execution of above program is :", end-start)
for r in result:
    print(r)





Enter the matrix size:  32


[[7.01028367 7.38456929 2.50132694 ... 9.48540253 8.51697586 9.85969687]
 [1.93782773 8.8739597  6.88575251 ... 2.97307915 1.66108286 1.3798085 ]
 [4.16915535 5.16271112 5.8662559  ... 6.76944604 9.81231771 8.14511578]
 ...
 [1.44508263 3.30414534 5.53302352 ... 1.55187353 5.42228744 3.51355381]
 [8.78702504 8.29229524 1.96907291 ... 9.45768531 5.2327116  7.51705053]
 [6.44120323 3.99360956 2.66565731 ... 1.88697984 3.79349672 3.58883793]]
[[1.33740565 6.7689935  6.08834419 ... 2.8583493  3.63631476 9.80752121]
 [8.28154486 9.79481546 8.03817111 ... 1.97206094 8.38495252 9.56257514]
 [9.39230892 3.80719286 4.97719847 ... 3.73615566 1.65120918 6.15265429]
 ...
 [6.73320547 6.96242424 3.06616426 ... 5.96185009 1.18185468 7.69043323]
 [6.17989729 2.91311646 5.99613886 ... 7.55486069 5.82159161 1.84578416]
 [7.11805138 3.61681093 8.95905234 ... 8.01930397 1.24039674 7.99958023]]
The complete time taken for execution of above program is : 0.08284902572631836
[707.38333418 819.63099476 918.2